resolver: lts-5.16

packages:
  - location: ./.
  - location:
      git: https://www.github.com/soenkehahn/wai-make-assets
      commit: c72a924
    extra-dep: true
  - location:
      git: https://www.github.com/mattjbray/elm-export
      commit: 3dfafc7a717003ff4374119ff6f60e5b56868d8f
    extra-dep: True
  - location:
      git: https://www.github.com/mattjbray/servant-elm
      commit: 36c90557d17d237e621cdcb4912ae9e4f25a9e59
    extra-dep: True

extra-deps:
  - servant-0.5
  - servant-client-0.5
  - servant-foreign-0.5
  - servant-server-0.5
  - warp-3.2.6
  - http2-1.6.0
